name: "Test on: release workflow"
on:
  release:
    types: [published]

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Test vars
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"