name: Check diff for license with Fossology

on:
  pull_request:

jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  # build-docker-image:
  #   name: Build Docker Image
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout this repository
  #       uses: actions/checkout@v3

  #     - name: Checkout specific branch of rajuljha/fossology repository
  #       uses: actions/checkout@v3
  #       with:
  #         repository: rajuljha/fossology
  #         ref: feat/automation/custom_keyword_conf_file
  #         path: fossology-repo

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Build Docker image
  #       run: |
  #         docker buildx build --load -t rjknightmare/fo-ci-test:latest -f fossology-repo/utils/automation/Dockerfile.ci fossology-repo

  #     - name: Save Docker image as artifact
  #       run: |
  #         docker save rjknightmare/fo-ci-test:latest | gzip > rjknightmare-fo-ci-test-latest.tar.gz
      
  #     - name: Upload Docker image artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: docker-image
  #         path: rjknightmare-fo-ci-test-latest.tar.gz


  check-license:
    name: Check license
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_ACTIONS \
            rjknightmare/fo-ci-test:latest "/bin/fossologyscanner" nomos ojo

  check-copyright:
    name: Check copyright
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Fossology Scanner with custom keywords
        if: ${{ vars.KEYWORD_CONF_FILE_PATH != '' }}
        run: |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -v ${{ github.workspace }}/${{ vars.KEYWORD_CONF_FILE_PATH }}:/bin/${{ vars.KEYWORD_CONF_FILE_PATH }} \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_ACTIONS \
            rjknightmare/fo-ci-test:latest "/bin/fossologyscanner" copyright keyword \
            --keyword-conf ${{ vars.KEYWORD_CONF_FILE_PATH }} 
      
      - name: Run fossology scanner
        if: ${{ vars.KEYWORD_CONF_FILE_PATH == '' }}
        run : |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_ACTIONS \
            rjknightmare/fo-ci-test:latest "/bin/fossologyscanner" copyright keyword
