name: Check foss-action

on:
  pull_request:

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform Fossology Scan
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Generate Python SBOM
        uses: rajuljha/foss-action-python@v1
        with: 
          environment: True

      - name: Test shell
        run: |
          echo ${{ steps.generate_sbom.outputs.sbom_file_path }}

      # - name: Run foss-action
      #   uses: rajuljha/fossology-action@v20
      #   with:
      #     scan_mode: "repo"
      #     scanners: "nomos ojo copyright keyword"
      #     # from_tag: "v005"
      #     # to_tag: "v004"
      #     allowlist_file_path: "whitelist.json"
      #     keyword_conf_file_path: "test_keyword.conf"
      #     report_format: "SPDX_YAML"
