name: Check foss-action

on:
  pull_request:

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform Fossology Scan
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Run foss-action
        uses: rajuljha/fossology-action@v1
        with:
          scan_mode: "repo"
          scanners: "nomos ojo copyright keyword"
          # from_tag: "v005"
          # to_tag: "v004"
          # keyword_conf_file_path: "test_keyword.conf"
          report_format: "SPDX_YAML" 
          # allowlist_file_path: "whitelist.json"
      
      - name: Random name generator
        uses: TGPSKI/name-generator-node-action@v2
        id: generator
        with:
          separator: '_'
          length: '4'
          style: 'upperCase'

      - name: test generator output
        run: echo "latest,${{ steps.generator.outputs.name }}"