name: Generate SBOM

on: push

jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Generate Python SBOM
    uses: CycloneDX/gh-python-generate-sbom@v2
    with:
      input: ./requirements.txt
      output: ./bom.json
      format: json